include $(TOPDIR)/rules.mk

LUCI_TITLE:=WAN Dashboard
LUCI_DEPENDS:=+luci-base +luci-compat
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=26

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
