#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/wan-led-monitor.sh
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    echo none > /sys/class/leds/red:status/trigger
    echo 1 > /sys/class/leds/red:status/brightness
    echo 0 > /sys/class/leds/green:status/brightness
    echo 0 > /sys/class/leds/blue:status/brightness
}
